### ISSUE TITLE
Add info how to use it.

### ISSUE THREAD

**Issue by vorg** [LukaszKrawczyk/clustering#5]
E.g.

```javascript
var DBSCAN = require('density-clustering').DBSCAN;
```

Seems obvious but different libraries have different conventions.

**Comment by vorg** [comment]
Just noticed that there are full examples on github but npm page https://www.npmjs.com/package/density-clustering

A new push is needed?

**Comment by LukaszKrawczyk** [comment]
@vorg Thank you for reporting this issue!
I've just publish new version (1.0.3) on NPM.

If you have some ideas on different way of initialising objects/using this library, feel free to send PR.
